version: 0.2

phases:
  install:
    commands:
      - printenv
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'dist/**/*'

post_build:
  commands:
    - aws cloudfront create-invalidation --distribution-id E20D70OS97EBDR --paths '/*'
